services:
  - type: web
    name: pruebaMudBlazor
    env: dotnet
    buildCommand: dotnet publish -c Release
    startCommand: dotnet pruebaMudBlazor/bin/Release/net8.0/publish/pruebaMudBlazor.dll
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: MONGODB_URI
        sync: false # Esto solicitará que ingreses el valor manualmente en el panel de Render
      - key: MONGODB_DATABASE
        value: pruebaMudBlazorDB
      - key: DOTNET_VERSION
        value: 9.0.x
    healthCheckPath: /health # Asegúrate de implementar un endpoint de comprobación de salud
    autoDeploy: true

databases:
  # Si necesitas una base de datos administrada por Render
  # Descomenta la siguiente sección
  # - name: pruebaMudBlazorDB
  #   plan: free
  #   type: redis