# Usar la imagen base de .NET 8.0
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080

# Usar la imagen SDK para build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Copiar el archivo de proyecto y restaurar dependencias
COPY ["*.csproj", "./"]
RUN dotnet restore

# Copiar el resto del código y construir
COPY . .
RUN dotnet build -c Release -o /app/build

# Publicar la aplicación
FROM build AS publish
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

# Imagen final
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

# Variable de entorno para el puerto
ENV ASPNETCORE_URLS=http://+:8080

ENTRYPOINT ["dotnet", "pruebaBlazor.dll"]